/* WARNING: THIS FILE IS MACHINE GENERATED.
 * DO NOT EDIT.
 */

// Generated by Berry Compiler v1.0.0_0.

/* Copyright (c) 2018 by CodeDojo and/or its individual developers. All rights reserved.
 * 
 * JUST BECAUSE THIS FILE IS ON YOUR COMPUTER/DISK/HARD DRIVE DOES NOT MEAN IT IS FREE
 * TO EDIT. DO NOT EDIT OR POST THIS FILE ANYWHERE ON THE INTERNET.
 */
#include <iostream>

int main(int argc, char** argv) {
  char memory[8] = {'\0', '\0', '\0', '\0', '\0', '\0', '\0', '\n'};
  int memoryPointer = 0;
  
  memoryPointer++; memoryPointer %= 8;
  memory[memoryPointer]++;
  memory[memoryPointer]++;
  memory[memoryPointer]++;
  memory[memoryPointer]++;
  
  while(memory[memoryPointer] != 0) {
    
    memoryPointer += 7;  memoryPointer %= 8;
    memory[memoryPointer]++;
    memory[memoryPointer]++;
    memory[memoryPointer]++;
    memory[memoryPointer]++;
    memory[memoryPointer]++;
    memory[memoryPointer]++;
    memory[memoryPointer]++;
    memory[memoryPointer]++;
    memoryPointer++; memoryPointer %= 8;
    memory[memoryPointer]--;
    
  }
  
  memoryPointer += 7;  memoryPointer %= 8;
  memory[memoryPointer]++;
  std::cout << memory[memoryPointer];
  memoryPointer += 7;  memoryPointer %= 8;
  std::cout << memory[memoryPointer];
  
  return 0;
}
